### ISSUE TITLE
How to set environment?

### ISSUE THREAD

**Issue by dyaskur** [tatablack/leaner-coffee-powerup#46]
I tried to create .env on main folder but when I run `npm run screenshots` return:
@Unable to proceed: the environment variables TRELLO_USERNAME and TRELLO_PASSWORD need to be set.

**Comment by tatablack** [comment]
Hi, @dyaskur.
`.env` files are not loaded automatically, so you'd have to export those variables in the shell you're running the command in.

May I ask what are you trying to do? To run the project locally, you don't need to set any environment variable. Those are only needed when generating screenshots, which is a task I'm happy to perform myself when new translations are submitted.

More instructions on how to run the project when working on the codebase can be found [here](https://github.com/tatablack/leaner-coffee-powerup/blob/master/CONTRIBUTING.md#your-first-code-contribution).
Let me know if you need more pointers. 🙂

**Comment by dyaskur** [comment]
The project is working perfectly, I just tried to make screenshot.  just curious maybe it's useful for future development.
  I tried below command:
```
TRELLO_USERNAME=user TRELLO_PASSWORD=pass BROWSERSTACK_USER=s_qIxrBs BROWSERSTACK_KEY=a npm run screenshots
```

return below error output:
```
 leancoffee-powerup@0.7.0 screenshots
> node ./tools/L10nImages/build-screenshots.js

2021-05-30 14:52:44 [--] BrowserStack tunnel established

2021-05-30 14:53:02 [--] ┌ Initiating login process
2021-05-30 14:53:03 [--] ├ Setting username
2021-05-30T07:53:15.667Z ERROR webdriver: Request failed with status 400 due to element not interactable: Element <input id="password" class="Input__InputElement-sc-1o6bj35-0 bfCuIo" type="password"> could not be scrolled into view
2021-05-30 14:53:15 [--] element not interactable: Element <input id="password" class="Input__InputElement-sc-1o6bj35-0 bfCuIo" type="password"> could not be scrolled into view
    at Object.getErrorFromResponseBody (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/webdriver/build/utils.js:189:12)
    at WebDriverRequest._request (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/webdriver/build/request.js:168:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Element.wrapCommandFn (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/@wdio/utils/build/shim.js:78:29)
    at async Element.wrapCommandFn (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/@wdio/utils/build/shim.js:78:29)
    at async Element.elementErrorHandlerCallbackFn (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/webdriverio/build/middlewares.js:23:32)
    at async Element.wrapCommandFn (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/@wdio/utils/build/shim.js:78:29)
    at async Element.wrapCommandFn (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/@wdio/utils/build/shim.js:78:29)
    at async Element.elementErrorHandlerCallbackFn (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/webdriverio/build/middlewares.js:23:32)
    at async Element.wrapCommandFn (/Users/yaskur/Sites/js/leaner-coffee-powerup/node_modules/@wdio/utils/build/shim.js:78:29)
```

What happen?

**Comment by tatablack** [comment]
It looks like the login form is not being displayed as expected.
If you go to https://automate.browserstack.com/dashboard/, you should be able to see screenshots taken by Browserstack while trying to perform the actions in the script.

I've actually updated this code less than a month ago, as the Trello login flow now goes to Atlassian first, and then back to Trello. I'll try to verify if it's still working for me, but I don't know that I'll have time this weekend. Probably some time next week, sorry. 😕

**Comment by dyaskur** [comment]
It's okay, I just curious how does it work to learn it. 

Actually, I thought it was caused by my code, because I added authorization in my project. but after I  clone again this repo 
 and test it, the problem still same.

By the way,  Thank you very much for your code. I use this repo to develop different product, I will replace most of your code(maybe near 90%). I just like your coding style and code structure. It's seem very good to create something like boilerplate/template from your project. I am new in typescript, never learn it or make project using it from scratch, just learn and make from other existing source codes.

**Comment by tatablack** [comment]
Thanks for the kind words. I had thought of creating a template for Trello plugins, as I couldn't find any when I created this project—I really should find the time at some point.

Learning by looking at other people's code, or even copy-pasting and modifying it to understand how it works, is a perfectly acceptable strategy. Nothing wrong with it. 🙂 

About this repo, one thing you should **NOT** take as an example is the lack of tests. I started the project just to learn how to create a Trello plugin, so at the beginning I didn't write any test, and now I really need to add them before I can add more features (otherwise the risk of breaking existing feature is too high).

Good luck with your learning! 👍🏻
